Review_Me/Models/ContentSellerUser.cs
using EntityLayer.Concrete;

namespace Review_Me.Models
{
    public class ContentSellerUser
    {
        public IEnumerable<User> Users { get; set; }
        public IEnumerable<Seller> Sellers { get; set; }
        public IEnumerable<Content> Contents { get; set; }
        public IEnumerable<Job> Jobs { get; set; }

        

        public Seller seller2 { get; set; }



    }
}

Review_Me/Models/ErrorViewModel.cs
namespace Review_Me.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Review_Me/Models/SellerReview.cs
namespace Review_Me.Models
{
    public class SellerReview
    {
        public int ID { get; set; }
        public string Sellername { get; set; }
    }
}

Review_Me/Controllers/ContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete.Context;
using DataAccessLayer.EntitiyFramework;
using DataAccessLayer.Repositories;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Review_Me.Models;

namespace Review_Me.Controllers
{
    public class ContentController : Controller
    {
        ContentManager cm = new ContentManager(new EFContentRepository());
        Context context = new Context();
        

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetContents()
        {
            ContentSellerUser su = new ContentSellerUser();
            //var content = cm.GetContents();
            //return View(content);
            su.Sellers = context.Sellers.ToList();
            su.Users = context.Users.ToList();
            su.Contents = context.Contents.ToList();
            su.Jobs = context.Jobs.ToList();
            return View(su);

        }

        public IActionResult AddContent()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult AddContent(Content content)
        {
            cm.ContentAdd(content);
            return RedirectToAction(nameof(GetContents));

        }
        
        public IActionResult Search(string searchTerm)
        {
            ContentSellerUser su = new ContentSellerUser();
            var searchResults = cm.GetContentByName(searchTerm);
            su.Sellers = context.Sellers.ToList();
            su.Users = context.Users.ToList();
            su.Contents = context.Contents.ToList();
            su.Jobs = context.Jobs.ToList();
            return View(su);

        }
        public IActionResult Remove(int id)
        {
            var value = cm.GetContentByID(id);
            cm.ContentRemove(value);
            return RedirectToAction(nameof(GetContents));
        }

        public IActionResult GetContentsJobs()
        {
            ContentSellerUser su = new ContentSellerUser();

            su.Sellers = context.Sellers.ToList();
            su.Users = context.Users.ToList();
            su.Contents = context.Contents.ToList();
            su.Jobs = context.Jobs.ToList();
            return View(su);
        }


        public IActionResult Update(int id)
        {
            
            var value = cm.GetContentByID(id);
            return View(value);
        }
        [HttpPost]
        public IActionResult Update(Content content)
        {
            
            cm.ContentUpdate(content);
            return RedirectToAction(nameof(GetContents));
        }


        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult Profile(int id)
        {
            //ContentSellerUser su = new ContentSellerUser();

            //su.Sellers = context.Sellers.ToList();
            //su.Users = context.Users.ToList();
            //su.Contents = context.Contents.ToList();
            //su.Jobs = context.Jobs.ToList();
            //return View(su);

            var value = cm.GetContentByID(id);
            return View(value);
        }


    }
}

Review_Me/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Review_Me.Models;
using System.Diagnostics;

namespace Review_Me.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult LoginRegister()
        {
            return View();
        }
    }
}

Review_Me/Controllers/ProfileController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete.Context;
using DataAccessLayer.EntitiyFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Review_Me.Models;

namespace Review_Me.Controllers
{
    public class ProfileController : Controller
    {
        ContentManager cm = new ContentManager(new EFContentRepository());
        SellerManager sm = new SellerManager(new EFSellerRepository());
        Context context = new Context();
        public IActionResult Index()
        {
            var value = sm.GetSellerWithJob();

            return View(value);
        }

        public IActionResult ProfilPage(int id)
        {
            ViewBag.i = id;    
            var value = sm.GetSellerID(id);

            return View(value);
        }
        public IActionResult AddReview()
        {

            return PartialView();
        }
        [HttpPost]
        public IActionResult AddReview(Content content)
        {
            
            content.UserID = 1;
            cm.ContentAdd(content);
            return RedirectToAction(nameof(Index));
        }

    }
}

Review_Me/Controllers/ReviewController.cs
 using BusinessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Review_Me.Controllers
{
    public class ReviewController : Controller
    {
        ContentManager sm = new ContentManager(new EFContentRepository());
        SellerManager cm = new SellerManager(new EFSellerRepository());
        public IActionResult Index()
        {
            var value = cm.GetSellerWithJob();

            return View(value);
            
        }
        public PartialViewResult PartialReview(int id)
        {
            var values = sm.GetContents(id);
            return PartialView(values);
        }

        public IActionResult AddReview()
        {
            
            return PartialView();
        }
        [HttpPost]
        public IActionResult AddReview(Content content)
        {
            content.SellerID = 1;
            content.UserID = 1;
            sm.ContentAdd(content);
            return RedirectToAction(nameof(Index));
        }


    }
}

Review_Me/Views/Content/AddContent.cshtml
@{
    Layout = null;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    @using (Html.BeginForm("AddContent","Content", FormMethod.Post))  
{
    
    <div class="col-12 grid-margin stretch-card"> 
        <div class="card" >
            <div class="card-body">
                <h4 class="card-title">Review Ekle</h4>
                <br />
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Başlık ekle</label>
                        <input type="text" class="form-control" name="Title">

                        <label class="mt-5">İçeriğinii girin</label>
                        <input type="text" class="form-control" name="ContentText">

                      

                        

                        <label class="mt-5">UserId</label>
                        <input type="text" class="form-control" name="UserID">

                        <label class="mt-5">Seller ID</label>
                        <input type="text" class="form-control" name="SellerID">
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg mt-4  mt-5">Kaydet</button>
                </form>
            </div>
        </div>
    </div>
}

Review_Me/Views/Content/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!doctype html>
<html lang="en">
<body>
<!-- header -->
<header id="site-header" class="fixed-top">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand mb-1" href="/Home/Index">
                    <img src="~/ReviewMe/ReviewMe/assets/images/yeniLogo3.png" style="width:220px; height:53px;">
            </a>
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
                <span class="navbar-toggler-icon fa icon-close fa-times"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/Home/Index">Ana Sayfa</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="/Profile/index">Değerlendirmeler</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link  active " href="/Content/Contact">İletişim</a>
                    </li>
                    <li class="nav-item ">
                            <a class="nav-link " href="/Home/LoginRegister">Kayıt Ol/Giriş Yap</a>
                    </li>

                </ul>
                <form action="#search" method="GET" class="d-flex search-header ms-lg-2">
                    <input class="form-control" type="search" placeholder="Ara..." aria-label="Search"
                           required>
                    <button class="btn btn-style" type="submit"><i class="fas fa-search"></i></button>
                </form>
            </div>
            <!-- toggle switch for light and dark theme -->
            <div class="cont-ser-position">
                <nav class="navigation">
                    <div class="theme-switch-wrapper">
                        <label class="theme-switch" for="checkbox">
                            <input type="checkbox" id="checkbox">
                            <div class="mode-container">
                                <i class="gg-sun"></i>
                                <i class="gg-moon"></i>
                            </div>
                        </label>
                    </div>
                </nav>
            </div>
            <!-- //toggle switch for light and dark theme -->
        </nav>
        
    </div>
</header>
<!-- inner banner -->
<section class="inner-banner py-5">
    <div class="w3l-breadcrumb py-lg-5">
        <div class="container pt-5 pb-sm-4 pb-2">
            <h4 class="inner-text-title font-weight-bold pt-5">Bize Ulaşın</h4>
            <ul class="breadcrumbs-custom-path">
                <li><a href="index.html">Ana Sayfa</a></li>
                <li class="active"><i class="fas fa-angle-right mx-2"></i>İletişim</li>
            </ul>
        </div>
    </div>
</section>
<!-- //inner banner -->
<!-- contact section -->
<section class="w3l-contact-2 py-5" id="contact">
    <div class="container py-lg-5 py-md-4 py-2">
        <div class="w3l-header-sec text-center mb-md-5 mb-4">
            <h3 class="title-style">Bize Ulaşın</h3>
        </div>
        <div class="contact-grids d-grid">
            <div class="contact-left-img">
                    <img src="~/ReviewMe/ReviewMe/assets/images/painter3.jpg" class="img-fluid radius-image" alt="">
            </div>
            <div class="contact-right">
                <form action="" method="post" class="signin-form">
                    <div class="input-grids">

                        <input type="text" name="w3lName" id="w3lName" placeholder="İsminiz"
                               class="contact-input" required="" />
                        <input type="email" name="w3lSender" id="w3lSender" placeholder="E-Posta Adresiniz"
                               class="contact-input" required="" />
                        <input type="text" name="w3lSubect" id="w3lSubect" placeholder="Konu"
                               class="contact-input" required="" />
                       
                    </div>
                    <div class="form-input">
                        <textarea name="w3lMessage" id="w3lMessage" placeholder="Mesajınızı Yazınız"
                                  required=""></textarea>
                    </div>
                    <div class="form-buttonhny text-lg-end">
                        <button class="btn btn-style btn-primary">Gönder</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="map-iframe mt-5 pt-md-4">
           @* <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d317718.69319292053!2d-0.3817765050863085!3d51.528307984912544!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8a00baf21de75%3A0x52963a5addd52a99!2sLondon%2C+UK!5e0!3m2!1sen!2spl!4v1562654563739!5m2!1sen!2spl"
                    width="100%" height="400" frameborder="0" style="border: 0px;" allowfullscreen=""></iframe>*@
                <iframe style="filter: invert(5%)" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d529.6584229676865!2d36.263888187621944!3d41.32625327262788!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x408878f9ab74f149%3A0xd5298ec24082799f!2s%C4%B0stiklal%2C%20889.%20Sk.%20No%3A8%2C%2055200%20Atakum%2FSamsun!5e0!3m2!1str!2str!4v1671876141888!5m2!1str!2str" width="100%" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</section>
<!-- //contact section -->
    
</body>

</html>

Review_Me/Views/Content/GetContents.cshtml
@{
    ViewData["Title"] = "GetContents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!doctype html>
<html lang="en">
 <!-- header -->
<header id="site-header" class="fixed-top">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand mb-1" href="/Home/Index">
                <img src="~/ReviewMe/ReviewMe/assets/images/yeniLogo3.png" style="width:220px; height:53px;">
            </a>
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
                <span class="navbar-toggler-icon fa icon-close fa-times"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/Home/Index">Ana Sayfa</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link active " href="/Content/GetContents">Değerlendirmeler</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="/Content/Contact">İletişim</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="/Home/LoginRegister">Kayıt Ol/Giriş Yap</a>
                    </li>

                </ul>
                <form action="#search" method="GET" class="d-flex search-header ms-lg-2">
                    <input class="form-control" type="search" placeholder="Ara..." aria-label="Search"
                           required>
                    <button class="btn btn-style" type="submit"><i class="fas fa-search"></i></button>
                </form>
            </div>
            <!-- toggle switch for light and dark theme -->
            <div class="cont-ser-position">
                <nav class="navigation">
                    <div class="theme-switch-wrapper">
                        <label class="theme-switch" for="checkbox">
                            <input type="checkbox" id="checkbox">
                            <div class="mode-container">
                                <i class="gg-sun"></i>
                                <i class="gg-moon"></i>
                            </div>
                        </label>
                    </div>
                </nav>
            </div>
            <!-- //toggle switch for light and dark theme -->
        </nav>
        
    </div>
</header>
<body>
    <!-- inner banner -->
    <section class="inner-banner py-5">
        <div class="w3l-breadcrumb py-lg-5">
            <div class="container pt-5 pb-sm-4 pb-2">
                <h4 class="inner-text-title font-weight-bold pt-5">Değerlendirmeler</h4>
                <ul class="breadcrumbs-custom-path">
                    <li><a href="index.html">Ana Sayfa</a></li>
                    <li class="active"><i class="fas fa-angle-right mx-2"></i>Değerlendirmeler</li>
                </ul>
            </div>
        </div>
    </section>
    <!-- //inner banner -->
    <!-- courses section -->
    <section class="w3l-courses py-5" id="courses">
        <div class="container py-lg-5 py-md-4 py-2">
            <h3 class="title-style text-center">En Fazla Değerlendirilen Hizmetler</h3>
            <div class="row d-flex justify-content-center">
                <div class="col-md-5 item mt-5">
                    <div class="card">
                        <div class="card-header p-0 position-relative">
                            <a href="classes.html" class="zoom d-block">
                                <img class="card-img-bottom d-block" src="~/ReviewMe/ReviewMe/assets/images/banner5.jpg" alt="Card image cap">
                            </a>
                        </div>
                        <div class="card-body course-details">
                            <div class="price-review d-flex justify-content-between mb-1align-items-center">
                                <p>Mehmet Usta</p>
                                <ul class="rating-star">
                                    <li><span class="fas fa-star"></span></li>
                                    <li><span class="fas fa-star"></span></li>
                                    <li><span class="fas fa-star"></span></li>
                                    <li><span class="fas fa-star"></span></li>
                                    <li><span class="fas fa-star-o"></span></li>
                                </ul>
                            </div>
                            <a href="classes.html" class="course-desc">
                                Lorem ipsum, dolor sit amet consectetur
                                adipisicing elit. Dolores impedit dolore est aut perferendis dolorum unde consectetur
                                eos. Labore, ducimus?
                            </a>
                            <div class="course-meta mt-4">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 item mt-5">
                    <div class="card">
                        <div class="card-header p-0 position-relative">
                            <a href="classes.html" class="zoom d-block">
                                <img class="card-img-bottom d-block" src="~/ReviewMe/ReviewMe/assets/images/banner5.jpg" alt="Card image cap">
                            </a>
                        </div>
                        <div class="card-body course-details">
                            <div class="price-review d-flex justify-content-between mb-1align-items-center">
                                <p>Mehmet Usta</p>
                                <ul class="rating-star">
                                    <li><span class="fas fa-star"></span></li>
                                    <li><span class="fas fa-star"></span></li>
                                    <li><span class="fas fa-star"></span></li>
                                    <li><span class="fas fa-star"></span></li>
                                    <li><span class="fas fa-star-o"></span></li>
                                </ul>
                            </div>
                            <a href="classes.html" class="course-desc">
                                Lorem ipsum, dolor sit amet consectetur
                                adipisicing elit. Dolores impedit dolore est aut perferendis dolorum unde consectetur
                                eos. Labore, ducimus?
                            </a>
                            <div class="course-meta mt-4">
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- //courses section -->
    <!-- content block1 -->
    <section class="w3l-content-block1 py-5" id="login">
        <div class="container py-md-5 py-4">
            <div class="row">
                <div class="col-lg-6 col-md-8 title-content py-md-5">
                    <h3 class="title-style text-white">Kayıt Ol Ve Değerlendir</h3>
                    <div class="mt-5" id="blur">
                        <a href="/Home/LoginRegister"><button id="show-login" onclick="toggle()" class="btn btn-style mt-4">Giriş Yap/Kayıt Ol</button></a>
                    </div>
                 
                </div>
            </div>
        </div>
    </section>
   
   

</body>

</html>

Review_Me/Views/Content/GetContentsJobs.cshtml
@model ContentSellerUser
@{
    ViewData["Title"] = "GetContentsJobs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!doctype html>
<html lang="en">


<!-- header -->
<header id="site-header" class="fixed-top">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand mb-1" href="/Home/Index">
                <img src ="~/ReviewMe/ReviewMe/assets/images/yeniLogo3.png" style="width:220px; height:53px;">
            </a>
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
                <span class="navbar-toggler-icon fa icon-close fa-times"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/Home/Index">Ana Sayfa</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link active " href="/Content/GetContents">Değerlendirmeler</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link  " href="/Content/Contact">İletişim</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="/Home/LoginRegister">Kayıt Ol/Giriş Yap</a>
                    </li>

                </ul>
                <form action="#search" method="GET" class="d-flex search-header ms-lg-2">
                    <input class="form-control" type="search" placeholder="Ara..." aria-label="Search"
                           required>
                    <button class="btn btn-style" type="submit"><i class="fas fa-search"></i></button>
                </form>
            </div>
            <!-- toggle switch for light and dark theme -->
            <div class="cont-ser-position">
                <nav class="navigation">
                    <div class="theme-switch-wrapper">
                        <label class="theme-switch" for="checkbox">
                            <input type="checkbox" id="checkbox">
                            <div class="mode-container">
                                <i class="gg-sun"></i>
                                <i class="gg-moon"></i>
                            </div>
                        </label>
                    </div>
                </nav>
            </div>
            <!-- //toggle switch for light and dark theme -->
        </nav>
        
    </div>
</header>

    <body>
<section class="inner-banner py-5">
    <div class="w3l-breadcrumb py-lg-5">
        <div class="container pt-5 pb-sm-4 pb-2">
            <h4 class="inner-text-title font-weight-bold pt-5">Değerlendirmeler</h4>
            <ul class="breadcrumbs-custom-path">
                <li><a href="index.html">Ana Sayfa</a></li>
                <li class="active"><i class="fas fa-angle-right mx-2"></i>Değerlendirmeler</li>
            </ul>
        </div>
    </div>
</section>
<!-- //inner banner -->
<!-- courses section -->
<section class="w3l-courses py-5" id="courses">
    <div class="container py-lg-5 py-md-4 py-2">
        <h3 class="title-style text-center">En Fazla Değerlendirilen Hizmetler</h3>
        
            
       
        <div class=" row justify-content-center ">
          @foreach (var item in Model.Jobs)
        {  

            <div class="col-lg-4 col-md-6 item mt-5">
                <div class="card">
                    <div class="card-header p-0 position-relative">
                        <a href="classes.html" class="zoom d-block">
                            <img class="card-img-bottom d-block" src="https://fastly.4sqi.net/img/general/600x600/87250539_ijQaX-nVB8nyOb4xoAFpr5kwT001bfnLWmQFa9202bM.jpg" alt="Card image cap">
                        </a>

                    </div>
                    <div class="card-body course-details">
                        <div class="price-review d-flex justify-content-between mb-1align-items-center">
                        </div>
                        <a href="/Content/GetContents" class="course-desc">@item.JobName </a>
                        <div class="course-meta mt-4">
                            <div class="meta-item course-lesson">
                                <span class="fas fa-users"></span>
                                <span class="meta-value"> 82  değerlendirme</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>} 

            
        </div>

    </div>
</section>
<!-- //courses section -->
<!-- content block1 -->
<section class="w3l-content-block1 py-5" id="login">
    <div class="container py-md-5 py-4">
        <div class="row">
            <div class="col-lg-6 col-md-8 title-content py-md-5">
                <h3 class="title-style text-white">Kayıt Ol Ve Değerlendir</h3>
                <div class="mt-5" id="blur">
                        <a href="/Home/LoginRegister"><button id="show-login" onclick="toggle()" class="btn btn-style mt-4">Giriş Yap/Kayıt Ol</button></a>
                    </div>
              
            </div>
        </div>
    </div>
</section>
 
</body>
</html>
 

Review_Me/Views/Content/Update.cshtml
@model EntityLayer.Concrete.Content
@{
    Layout = null;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

 <form method="post" asp-action="Update">
    <input asp-for="ContentID" hidden />
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">İçeriği Güncelle</h4>
                <br />
        </div>
         <form class="forms-sample">
                <div class="form-group">

                    <label>İçerik Adı </label>
                    <input asp-for="Title" class="form-control" />

                    <label class="mt-5">İçeriği girin</label>
                    <input asp-for="ContentText" class="form-control" />

                    

                    <label class="mt-5">Userid</label>
                    <input asp-for="UserID" class="form-control" />

                    <label class="mt-5">Sellerid</label>
                    <input asp-for="SellerID" class="form-control" />
                </div>

                <button type="submit" class="btn btn-outline-info mt-5">Güncelle</button>
            </form>

    </div>
    </div>
</form>

Review_Me/Views/Review/AddReview.cshtml
@using EntityLayer.Concrete
@model List<Seller>


    @foreach (var item in Model)
    {
        
   
<div class="form-comment mt-5">
                            <h3 class="post-title mb-4">Değerlendirme Ekle</h3>
                            <form action="/Profile/AddReview/" method="POST">
                                <div class="form-group">
                                    <div class="row">                                   
                                    </div>
                                    <textarea class="form-control" placeholder="Başlık"
                                              id="exampleFormControlTextarea1" rows="4" name = "Title"></textarea>
                                              <textarea class="form-control" placeholder="İçerik"
                                              id="exampleFormControlTextarea1" rows="4" name ="ContentText"></textarea>
                                              <input type="hidden" name="sellerId" value="@item.SellerID" />
                                    <div class="text-end ms-auto">
                                        <button class="btn btn-style mt-2" type="submit">
                                            Değerlendir
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="pagination-wrapper mt-5 pt-lg-3 text-center">
                            <ul class="page-pagination">
                                <li><span aria-current="page" class="page-numbers current">1</span></li>
                                <li><a class="page-numbers" href="#url">2</a></li>
                                <li><a class="page-numbers" href="#url">3</a></li>
                                <li><a class="next" href="#url">Next <span class="fa fa-angle-right"></span></a></li>
                            </ul>
            </div>  }    

Review_Me/Views/Shared/Components/ReviewList/Default.cshtml
@model IEnumerable<SellerReview>


@foreach (var item in Model)
{
    <p>@item.ID</p>
    <p>@item.Sellername</p>
}